-- !! AUTO GENERATED BY WATCH.JS - DO NOT MODIFY MANUALLY !!
return {
    ["combat"] = {
    },
    ["blatant"] = {
        "games/1_8arena/modules/blatant/Speed",
    },
    ["Render"] = {
    },
    ["Utility"] = {
    },
    ["World"] = {
    },
    ["Inventory"] = {
    },
    ["Minigames"] = {
    },
}
