-- !! AUTO GENERATED BY WATCH.JS - DO NOT MODIFY MANUALLY !!
return {
    ["combat"] = {
    },
    ["blatant"] = {
    },
    ["Render"] = {
    },
    ["Utility"] = {
    },
    ["World"] = {
    },
    ["Inventory"] = {
    },
    ["Minigames"] = {
    },
}
