const chokidar = require('chokidar');
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

console.log('👀 src/ games/ フォルダを監視中... (Ctrl+C で停止)');

// 🌟 ① 各ゲームフォルダ直下の base.lua を自動一括生成する関数
function generateGameBaseFiles() {
    const gamesPath = path.join(__dirname, 'src', 'games');
    if (!fs.existsSync(gamesPath)) return;

    // src/games/ 以下のすべてのサブディレクトリ（universal、1.8arena、Bridge Duel、hoplex、pillars_of_fortune）を取得
    const gameFolders = fs.readdirSync(gamesPath).filter(file => {
        const fullPath = path.join(gamesPath, file);
        return fs.statSync(fullPath).isDirectory();
    });

    gameFolders.forEach(gameFolder => {
        const modulesPath = path.join(gamesPath, gameFolder, 'modules');
        const basePath = path.join(gamesPath, gameFolder, 'base.lua');

        // Main.lua の読み込みキー（大文字小文字の規格）に完全に一致させます
        const categories = ['combat', 'blatant', 'Render', 'Utility', 'World', 'Inventory', 'Minigames'];

        let luaContent = `-- !! AUTO GENERATED BY WATCH.JS - DO NOT MODIFY MANUALLY !!\n`;
        luaContent += `return {\n`;

        categories.forEach(category => {
            // 大文字・小文字の物理フォルダ名の揺れに対応（実際にあるパスを検知）
            const categoryDirName = fs.existsSync(path.join(modulesPath, category)) ? category : 
                                    fs.existsSync(path.join(modulesPath, category.toLowerCase())) ? category.toLowerCase() : 
                                    fs.existsSync(path.join(modulesPath, category.charAt(0).toUpperCase() + category.slice(1))) ? category.charAt(0).toUpperCase() + category.slice(1) : 
                                    category;

            // 返却キーは Main.lua の期待する大文字・小文字キーに統一して出力
            luaContent += `    ["${category}"] = {\n`;
            const categoryPath = path.join(modulesPath, categoryDirName);

            if (fs.existsSync(categoryPath)) {
                const files = fs.readdirSync(categoryPath).filter(file => file.endsWith('.lua'));
                files.forEach(file => {
                    const moduleName = path.basename(file, '.lua');
                    // requireの解決パスを動的に生成
                    // require() ではなく、HTTPで取得するためのファイルパス（文字列）を書き出すように変更します
luaContent += `        "games/${gameFolder}/modules/${categoryDirName}/${moduleName}",\n`;
                });
            }

            luaContent += `    },\n`;
        });

        luaContent += `}\n`;

        fs.writeFileSync(basePath, luaContent);
        console.log(`🤖 [Auto-Base] games/${gameFolder}/base.lua updated!`);
    });
}

// 🌟 ② ファイル監視と自動ビルド
chokidar.watch('./src', { ignoreInitial: true }).on('all', (event, filePath) => {
    // 自身の更新を無視（ビルドの無限ループを防止）
    if (filePath.includes('base.lua') || filePath.includes('bundle.lua')) return;

    console.log(`\n🔄 変更検出: ${filePath}`);
    try {
        const normalizedPath = filePath.replace(/\\/g, '/');
        
        // games フォルダ内のモジュールに変更があった場合にベースファイルを自動更新
        const isGamesChange = normalizedPath.includes('games/') && normalizedPath.includes('modules');

        if (isGamesChange) {
            generateGameBaseFiles();
        }

        execSync(
            'npx luabundler bundle ./src/Main.lua -p ./src/?.lua -p ./src/?/init.lua -o ./dist/bundle.lua',
            { stdio: 'inherit' }
        );
        console.log('✅ dist/bundle.lua を更新しました!');
    } catch (e) {
        console.error('❌ ビルド失敗', e);
    }
});