-- !! AUTO GENERATED BY WATCH.JS - DO NOT MODIFY MANUALLY !!
return {
    ["combat"] = {
    },
    ["blatant"] = {
        "games/lucky_blocks/modules/blatant/Killaura",
    },
    ["Render"] = {
    },
    ["Utility"] = {
    },
    ["World"] = {
    },
    ["Inventory"] = {
    },
    ["Minigames"] = {
    },
}
