-- !! AUTO GENERATED BY WATCH.JS - DO NOT MODIFY MANUALLY !!
return {
    ["combat"] = {
        require("games.universal.modules.combat.AimAssist"),
    },
    ["blatant"] = {
        require("games.universal.modules.blatant.HitBoxes"),
    },
    ["Render"] = {
    },
    ["Utility"] = {
    },
    ["World"] = {
    },
    ["Inventory"] = {
    },
    ["Minigames"] = {
    },
}
