-- !! AUTO GENERATED BY WATCH.JS - DO NOT MODIFY MANUALLY !!
return {
    ["combat"] = {
        "games/universal/modules/combat/AimAssist",
    },
    ["blatant"] = {
        "games/universal/modules/blatant/HitBoxes",
    },
    ["Render"] = {
    },
    ["Utility"] = {
    },
    ["World"] = {
    },
    ["Inventory"] = {
    },
    ["Minigames"] = {
    },
}
